### ISSUE TITLE
Dots are not center 

### ISSUE THREAD

**Issue by Cristy4** [EmilioPelaez/ScrollingPageControl#4] opened 2020-09-14 18:55 UTC
Dots are not centered
I have constraints 8 for leading 8 for trailing and even center on X
![Simulator Screen Shot - iPhone X - 2020-09-14 at 13 48 24](https://user-images.githubusercontent.com/30754740/93126452-f8052900-f691-11ea-87ad-1066afe12f79.png)

**Comment by Arbios** [comment] 2020-10-29 10:26
You need to set centerDots, for example pageControl.centerDots = 3

**Comment by EmilioPelaez** [comment] 2020-10-29 14:53
@Cristy4 I tried multiple configurations and I couldn't reproduce what you're seeing. Can you double check your constraints?
<img width="448" alt="Screen Shot 2020-10-29 at 15 48 17" src="https://user-images.githubusercontent.com/140234/97589852-5007ad00-19fe-11eb-9709-3f47439d7b2c.png">

**Comment by EmilioPelaez** [comment] 2020-11-01 13:14
@Cristy4 I'm closing this issue but feel free to reopen it with a small sample project if you can reproduce it.

**Closed as completed by EmilioPelaez** 2020-11-01 13:14 UTC

**Comment by tallot13** [comment] 2021-03-18 10:41
from example project, size 8 and size 2, constraint not changed(center)
<img width="336" alt="Снимок экрана 2021-03-18 в 13 39 14" src="https://user-images.githubusercontent.com/48832276/111613322-71bbd200-87ef-11eb-899f-7e6da8baf408.png">
<img width="341" alt="Снимок экрана 2021-03-18 в 13 38 39" src="https://user-images.githubusercontent.com/48832276/111613332-741e2c00-87ef-11eb-9aee-1cfbaf45427c.png">m
